version: "3.8"

services:
  tasks-app:
    build: ./
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=postgres
    networks:
      - new

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasks
      - POSTGRES_USER=postgres
    ports:
      - 5436:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tasks"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - new

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:postgres@db:5432/tasks?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - new

networks:
  new:
