port: "8000"
db: 
  host: "db"
  port: "5432"
  username: "postgres"
  dbname: "tasks"
  sslmode: "disable"
mail:
  from: "NikitaIshenko905@gmail.com"
  password: "izgjavwnuvkrxhfh"
  host: "smtp.gmail.com"
  port: "587"